// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Struct
	Value
	ListValue
	Request
	Response
	Query
	Result
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// `NullValue` is a singleton enumeration to represent the null value for the
// `Value` type union.
//
//  The JSON representation for `NullValue` is JSON `null`.
type NullValue int32

const (
	// Null value.
	NullValue_NULL_VALUE NullValue = 0
)

var NullValue_name = map[int32]string{
	0: "NULL_VALUE",
}
var NullValue_value = map[string]int32{
	"NULL_VALUE": 0,
}

func (x NullValue) String() string {
	return proto.EnumName(NullValue_name, int32(x))
}
func (NullValue) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The JSON representation for `Struct` is JSON object.
type Struct struct {
	// Unordered map of dynamically typed values.
	Fields map[string]*Value `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Struct) Reset()                    { *m = Struct{} }
func (m *Struct) String() string            { return proto.CompactTextString(m) }
func (*Struct) ProtoMessage()               {}
func (*Struct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Struct) GetFields() map[string]*Value {
	if m != nil {
		return m.Fields
	}
	return nil
}

// `Value` represents a dynamically typed value which can be either
// null, a number, a string, a boolean, a recursive struct value, or a
// list of values. A producer of value is expected to set one of that
// variants, absence of any variant indicates an error.
//
// The JSON representation for `Value` is JSON value.
type Value struct {
	// The kind of value.
	//
	// Types that are valid to be assigned to Kind:
	//	*Value_NullValue
	//	*Value_NumberValue
	//	*Value_StringValue
	//	*Value_BoolValue
	//	*Value_StructValue
	//	*Value_ListValue
	Kind isValue_Kind `protobuf_oneof:"kind"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NullValue struct {
	NullValue NullValue `protobuf:"varint,1,opt,name=null_value,enum=server.NullValue,oneof"`
}
type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,oneof"`
}
type Value_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,oneof"`
}
type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,oneof"`
}
type Value_StructValue struct {
	StructValue *Struct `protobuf:"bytes,5,opt,name=struct_value,oneof"`
}
type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,6,opt,name=list_value,oneof"`
}

func (*Value_NullValue) isValue_Kind()   {}
func (*Value_NumberValue) isValue_Kind() {}
func (*Value_StringValue) isValue_Kind() {}
func (*Value_BoolValue) isValue_Kind()   {}
func (*Value_StructValue) isValue_Kind() {}
func (*Value_ListValue) isValue_Kind()   {}

func (m *Value) GetKind() isValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Value) GetNullValue() NullValue {
	if x, ok := m.GetKind().(*Value_NullValue); ok {
		return x.NullValue
	}
	return NullValue_NULL_VALUE
}

func (m *Value) GetNumberValue() float64 {
	if x, ok := m.GetKind().(*Value_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetKind().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Value) GetBoolValue() bool {
	if x, ok := m.GetKind().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *Value) GetStructValue() *Struct {
	if x, ok := m.GetKind().(*Value_StructValue); ok {
		return x.StructValue
	}
	return nil
}

func (m *Value) GetListValue() *ListValue {
	if x, ok := m.GetKind().(*Value_ListValue); ok {
		return x.ListValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_NullValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_StructValue)(nil),
		(*Value_ListValue)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// kind
	switch x := m.Kind.(type) {
	case *Value_NullValue:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.NullValue))
	case *Value_NumberValue:
		b.EncodeVarint(2<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.NumberValue))
	case *Value_StringValue:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Value_BoolValue:
		t := uint64(0)
		if x.BoolValue {
			t = 1
		}
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Value_StructValue:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StructValue); err != nil {
			return err
		}
	case *Value_ListValue:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Value.Kind has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // kind.null_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Kind = &Value_NullValue{NullValue(x)}
		return true, err
	case 2: // kind.number_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Kind = &Value_NumberValue{math.Float64frombits(x)}
		return true, err
	case 3: // kind.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Kind = &Value_StringValue{x}
		return true, err
	case 4: // kind.bool_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Kind = &Value_BoolValue{x != 0}
		return true, err
	case 5: // kind.struct_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Struct)
		err := b.DecodeMessage(msg)
		m.Kind = &Value_StructValue{msg}
		return true, err
	case 6: // kind.list_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListValue)
		err := b.DecodeMessage(msg)
		m.Kind = &Value_ListValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// kind
	switch x := m.Kind.(type) {
	case *Value_NullValue:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.NullValue))
	case *Value_NumberValue:
		n += proto.SizeVarint(2<<3 | proto.WireFixed64)
		n += 8
	case *Value_StringValue:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Value_BoolValue:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += 1
	case *Value_StructValue:
		s := proto.Size(x.StructValue)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_ListValue:
		s := proto.Size(x.ListValue)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// `ListValue` is a wrapper around a repeated field of values.
//
// The JSON representation for `ListValue` is JSON array.
type ListValue struct {
	// Repeated field of dynamically typed values.
	Values []*Value `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *ListValue) Reset()                    { *m = ListValue{} }
func (m *ListValue) String() string            { return proto.CompactTextString(m) }
func (*ListValue) ProtoMessage()               {}
func (*ListValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListValue) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type Request struct {
	Dsn      string `protobuf:"bytes,1,opt,name=dsn" json:"dsn,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port     uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Database string `protobuf:"bytes,4,opt,name=database" json:"database,omitempty"`
	User     string `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
	Password string `protobuf:"bytes,6,opt,name=password" json:"password,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Response struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Query struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Result struct {
	Result uint32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	D      *Struct `protobuf:"bytes,2,opt,name=d" json:"d,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Result) GetD() *Struct {
	if m != nil {
		return m.D
	}
	return nil
}

func init() {
	proto.RegisterType((*Struct)(nil), "server.Struct")
	proto.RegisterType((*Value)(nil), "server.Value")
	proto.RegisterType((*ListValue)(nil), "server.ListValue")
	proto.RegisterType((*Request)(nil), "server.Request")
	proto.RegisterType((*Response)(nil), "server.Response")
	proto.RegisterType((*Query)(nil), "server.Query")
	proto.RegisterType((*Result)(nil), "server.Result")
	proto.RegisterEnum("server.NullValue", NullValue_name, NullValue_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Neo5G service

type Neo5GClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Neo5G_ConnectClient, error)
	Execute(ctx context.Context, opts ...grpc.CallOption) (Neo5G_ExecuteClient, error)
}

type neo5GClient struct {
	cc *grpc.ClientConn
}

func NewNeo5GClient(cc *grpc.ClientConn) Neo5GClient {
	return &neo5GClient{cc}
}

func (c *neo5GClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Neo5G_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Neo5G_serviceDesc.Streams[0], c.cc, "/server.neo5g/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &neo5GConnectClient{stream}
	return x, nil
}

type Neo5G_ConnectClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type neo5GConnectClient struct {
	grpc.ClientStream
}

func (x *neo5GConnectClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *neo5GConnectClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *neo5GClient) Execute(ctx context.Context, opts ...grpc.CallOption) (Neo5G_ExecuteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Neo5G_serviceDesc.Streams[1], c.cc, "/server.neo5g/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &neo5GExecuteClient{stream}
	return x, nil
}

type Neo5G_ExecuteClient interface {
	Send(*Query) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type neo5GExecuteClient struct {
	grpc.ClientStream
}

func (x *neo5GExecuteClient) Send(m *Query) error {
	return x.ClientStream.SendMsg(m)
}

func (x *neo5GExecuteClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Neo5G service

type Neo5GServer interface {
	Connect(Neo5G_ConnectServer) error
	Execute(Neo5G_ExecuteServer) error
}

func RegisterNeo5GServer(s *grpc.Server, srv Neo5GServer) {
	s.RegisterService(&_Neo5G_serviceDesc, srv)
}

func _Neo5G_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Neo5GServer).Connect(&neo5GConnectServer{stream})
}

type Neo5G_ConnectServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type neo5GConnectServer struct {
	grpc.ServerStream
}

func (x *neo5GConnectServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *neo5GConnectServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Neo5G_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Neo5GServer).Execute(&neo5GExecuteServer{stream})
}

type Neo5G_ExecuteServer interface {
	Send(*Result) error
	Recv() (*Query, error)
	grpc.ServerStream
}

type neo5GExecuteServer struct {
	grpc.ServerStream
}

func (x *neo5GExecuteServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *neo5GExecuteServer) Recv() (*Query, error) {
	m := new(Query)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Neo5G_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.neo5g",
	HandlerType: (*Neo5GServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Neo5G_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Execute",
			Handler:       _Neo5G_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x53, 0x4d, 0x6f, 0x13, 0x3d,
	0x10, 0x8e, 0x93, 0xec, 0x26, 0x3b, 0x69, 0xf3, 0xe6, 0xb5, 0x10, 0xaa, 0x02, 0x08, 0xb4, 0x08,
	0x29, 0xe2, 0x10, 0x55, 0x5b, 0x21, 0x21, 0x0e, 0x48, 0x14, 0x05, 0xf5, 0x10, 0x55, 0xc2, 0xa8,
	0x3d, 0x70, 0x89, 0x92, 0xac, 0x09, 0x51, 0xb6, 0x76, 0x6a, 0x7b, 0x0b, 0xfd, 0x03, 0x5c, 0x39,
	0xf2, 0x77, 0x19, 0x7f, 0x6d, 0x4b, 0x6f, 0xcf, 0xcc, 0x3c, 0xf3, 0xf1, 0xcc, 0xd8, 0x70, 0xa0,
	0xb9, 0xba, 0xe1, 0x6a, 0xba, 0x57, 0xd2, 0x48, 0x9a, 0x7a, 0x2b, 0xff, 0x45, 0x20, 0xfd, 0x62,
	0x54, 0xbd, 0x36, 0xb4, 0x80, 0xf4, 0xdb, 0x96, 0x57, 0xa5, 0x3e, 0x22, 0x2f, 0x3a, 0x93, 0x41,
	0x31, 0x9e, 0x86, 0x0c, 0x1f, 0x9f, 0x7e, 0x72, 0xc1, 0x99, 0x30, 0xea, 0x96, 0x05, 0xe6, 0xf8,
	0x0c, 0x06, 0xf7, 0xdc, 0x74, 0x04, 0x9d, 0x1d, 0xbf, 0xc5, 0x7c, 0x32, 0xc9, 0x98, 0x85, 0xf4,
	0x25, 0x24, 0x37, 0xcb, 0xaa, 0xe6, 0x47, 0x6d, 0xf4, 0x0d, 0x8a, 0xc3, 0x58, 0xf3, 0xd2, 0x3a,
	0x99, 0x8f, 0xbd, 0x6b, 0xbf, 0x25, 0xf9, 0x9f, 0x36, 0x24, 0xce, 0x89, 0x73, 0x80, 0xa8, 0xab,
	0x6a, 0xe1, 0xf3, 0x6c, 0xad, 0x61, 0xf1, 0x7f, 0xcc, 0x3b, 0xc7, 0x88, 0xa3, 0x9d, 0xb5, 0x58,
	0x26, 0xa2, 0x81, 0x6d, 0x0e, 0x44, 0x7d, 0xb5, 0xe2, 0x6a, 0x71, 0xd7, 0x8d, 0x20, 0x65, 0xe0,
	0xbd, 0x0d, 0x49, 0x1b, 0xb5, 0x15, 0x9b, 0x40, 0xea, 0xd8, 0x31, 0x2d, 0xc9, 0x7b, 0x3d, 0xe9,
	0x39, 0xc0, 0x4a, 0xca, 0xd8, 0xbd, 0x8b, 0x94, 0xbe, 0x6d, 0x65, 0x7d, 0x9e, 0x70, 0xe2, 0xaa,
	0xe0, 0x42, 0x02, 0x25, 0x71, 0xc2, 0x86, 0xff, 0x2e, 0x2b, 0x54, 0x45, 0xd4, 0x68, 0xaa, 0xb6,
	0x3a, 0xa6, 0xa4, 0x2e, 0xa5, 0xd1, 0x34, 0xc7, 0x48, 0xa3, 0xa9, 0x8a, 0xc6, 0x69, 0x0a, 0xdd,
	0xdd, 0x56, 0x94, 0x79, 0x01, 0x59, 0xc3, 0xa0, 0xaf, 0x20, 0x75, 0x35, 0xe2, 0x91, 0x1e, 0x2c,
	0x34, 0x04, 0xf3, 0xdf, 0x04, 0x7a, 0x8c, 0x5f, 0x23, 0x34, 0xf6, 0x28, 0xa5, 0x16, 0xf1, 0x28,
	0x08, 0x29, 0x85, 0xee, 0x77, 0xa9, 0x8d, 0xdb, 0x52, 0xc6, 0x1c, 0xb6, 0xbe, 0xbd, 0x54, 0xc6,
	0x2d, 0xe5, 0x90, 0x39, 0x4c, 0xc7, 0xd0, 0x2f, 0x97, 0x66, 0xb9, 0x5a, 0x6a, 0xbf, 0x89, 0x8c,
	0x35, 0xb6, 0xe5, 0xd7, 0xd8, 0xda, 0xc9, 0xc7, 0x1a, 0x16, 0x5b, 0xfe, 0x7e, 0xa9, 0xf5, 0x0f,
	0xa9, 0x4a, 0xa7, 0x11, 0xf9, 0xd1, 0xce, 0x8f, 0xa1, 0xcf, 0xb8, 0xde, 0x4b, 0xe1, 0x73, 0xd7,
	0xb2, 0xf4, 0xb7, 0xc5, 0x5e, 0x16, 0xdb, 0x29, 0xaf, 0xf4, 0x26, 0x8c, 0x64, 0x61, 0xfe, 0x0c,
	0x92, 0xcf, 0x35, 0xc7, 0x57, 0xf5, 0x08, 0x92, 0x6b, 0x0b, 0x82, 0x04, 0x6f, 0xe4, 0xef, 0x21,
	0xc5, 0x82, 0x75, 0x65, 0xe8, 0x63, 0x48, 0x95, 0x43, 0xa1, 0x60, 0xb0, 0xe8, 0x53, 0x20, 0x65,
	0x78, 0x77, 0x0f, 0xce, 0xc3, 0x48, 0xf9, 0xfa, 0x09, 0x64, 0xcd, 0x63, 0xa2, 0x43, 0x80, 0xf3,
	0x8b, 0xf9, 0x7c, 0x71, 0xf9, 0x61, 0x7e, 0x31, 0x1b, 0xb5, 0x8a, 0x1d, 0x24, 0x82, 0xcb, 0x37,
	0x1b, 0x3c, 0x5c, 0xef, 0xa3, 0x14, 0x82, 0xe3, 0xff, 0xf8, 0x2f, 0xd6, 0x08, 0x8b, 0x1d, 0x8f,
	0xee, 0x1c, 0x5e, 0x58, 0xde, 0x9a, 0x90, 0x63, 0x42, 0xa7, 0xd0, 0x9b, 0xfd, 0xe4, 0xeb, 0xda,
	0x70, 0xda, 0x9c, 0xc7, 0x29, 0x19, 0x0f, 0xef, 0x65, 0xe0, 0x84, 0x9e, 0x7f, 0xda, 0xff, 0x1a,
	0x7e, 0xe3, 0x2a, 0x75, 0x9f, 0xf3, 0xe4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x00, 0x73,
	0xf1, 0xac, 0x03, 0x00, 0x00,
}
